services:
  Deployee\Plugins\Install\Commands\InstallCommand:
    class: Deployee\Plugins\Install\Commands\InstallCommand
    tags: ['console.command']
    calls:
      - method: setDeployDefinitionPath
        arguments: ['%deploy_definition_path%']
      - method: setEventDispatcher
        arguments: ['@Symfony\Component\EventDispatcher\EventDispatcherInterface']